name: mds-approximations
channels:
- qiime2
- conda-forge
- defaults
- bioconda
- biocore
- anaconda
dependencies:
- scikit-bio
- click=6.7 # install from anaconda channel
- python=3.5
- numpy
- scikit-learn=0.19.1
- scipy
- pandas
- jupyter
- matplotlib
- gneiss=0.4.2
- pytz
- tensorflow
- pip
# also need to install bayesian-regression:
- pip:
  - bayesian_regression-0.1-py3-none-any.whl
